### ISSUE TITLE
hotios plex paths changed

### ISSUE THREAD

**Issue by jpalenz77** [themepark-dev/theme.park#511]
here is the new one:

/usr/lib/plexmediaserver/Resources/Plug-ins-07e0d4a7e/WebClient.bundle/Contents/Resources/index.html

thanks

**Describe the bug**

**Theme Install Method** (Don't skip)
- Docker run / Compose Config
  - If using docker mods share your COMPLETE container logs..
- Webserver subfilter Config
- Stylus Config

**Application Info** (Don't skip)
- Version
- Branch
- Container
- Logs

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (If applicable) (please complete the following information):**

**Smartphone (If applicable) (please complete the following information):**

**Additional context**

**Comment by balogun14** [comment]
@jpalenz77 can you explain this a bit more

**Comment by GilbN** [comment]
@jpalenz77 try the latest version of the docker mod. 

@balogun14 the https://hotio.dev/containers/plex/ image install path had changed so the script failed to sed the html file.

**Comment by jpalenz77** [comment]
> @jpalenz77 try the latest version of the docker mod/script.
> 
> @balogun14 the https://hotio.dev/containers/plex/ image install path had changed so the script failed to sed the html file.

All good now, thanks!
