### ISSUE TITLE
unRAID Community Apps Repo should be updated

### ISSUE THREAD

**Issue by Tyree** [themepark-dev/theme.park#517]
I just had issues with a bunch of containers that utilize the theme-park container on unRAID.
I removed the theme-park container and reinstalled it from scratch from Community Apps. Containers still wouldn't load, choking on the TP files.
I then came here and checked the latest TP release and saw the repo endpoint had changed. I updated the endpoint on the unRAID container and then all he other containers would start.
So, just a note to say that the unRAID CA endpoint still says "ghcr.io/gilbn/theme.park" and should be updated so it pulls the correct files.

THANKS!

**Comment by GilbN** [comment]
Should be updated now.
