### ISSUE TITLE
Footer Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [themepark-dev/theme.park#519]
The current design of the footer is nice but it can be improved by:
1. removing excessive space below footer
2. working on background and style of footer text.

This way we can make footer look-and-feel even better.

## Screenshots

**Current Design**

![input (1)](https://github.com/themepark-dev/theme.park/assets/115794049/b3fb31d0-36a9-4c3d-8d47-83620542d2f6)

**Expected Updated Design**

![input (2)](https://github.com/themepark-dev/theme.park/assets/115794049/a07d3896-d718-46ef-bde8-b1e984cd95ef)

**Comment by arezooHND** [comment]
Hi, assign this issue to me.

**Comment by GilbN** [comment]
@iamRabia-N If you want to contribute, contribute to the CSS themes etc. Closing this 😀
