### ISSUE TITLE
Radarr Theme Organizr Seems Broken

### ISSUE THREAD

**Issue by SmokeyBR** [themepark-dev/theme.park#520]
**Describe the bug**
I can change theme of all my other apps except radarr not working or rather working on some parts.

**Theme Install Method** (Don't skip)
variables.conf
```
map $host $theme {
    default organizr; # e.g. default organizr
}
```
theme-park.conf
```
    proxy_set_header Accept-Encoding "";
    sub_filter
    '</head>'
    '<link rel="stylesheet" type="text/css" href="https://develop.theme-park.dev/css/base/$app/$app-base.css">
    <link rel="stylesheet" type="text/css" href="https://develop.theme-park.dev/css/theme-options/$theme.css">
    </head>';
    sub_filter_once on;
```
arr.conf
```
location /sonarr/ {
	<removed>
	
	set $app sonarr;
	include <removed>/theme-park.conf;
}
location /radarr/ {
	<removed>
	
	set $app radarr;
	include <removed>/theme-park.conf;
}
```
**Application Info** (Don't skip)
- 5.0.3.8127
- docker

**Expected behavior**
Im expecting to see the organizr theme for radarr as represented on website so i can have all my arr apps with the same look.

**Screenshots**
organizr theme activated
![Screenshot 2023-10-18 at 19-43-56 Radarr](https://github.com/themepark-dev/theme.park/assets/19333582/afe27e0c-2918-43fc-aaea-5de272f21084)
![Screenshot 2023-10-18 at 19-43-21 Sonarr](https://github.com/themepark-dev/theme.park/assets/19333582/9c342c84-dad0-47eb-96e5-dfee33960cb4)

nord theme activated (for testing)
![Screenshot 2023-10-18 at 19-44-52 Radarr](https://github.com/themepark-dev/theme.park/assets/19333582/b9ddcb0c-f7b9-45f1-850d-1b36ff19ab18)
![Screenshot 2023-10-18 at 19-44-43 Sonarr](https://github.com/themepark-dev/theme.park/assets/19333582/2f6dc1c6-2594-4ace-a97a-d7462d18c46a)

**Comment by GilbN** [comment]
Follow the docs here. https://docs.theme-park.dev/themes/radarr/#setup

**Comment by SmokeyBR** [comment]
so i guess i had to only change where was </head> to </body> weird i did follow the doc instructions to begin with.
a heads up the way its formatted on the doc does break nginx.

```
proxy_set_header Accept-Encoding "";
sub_filter
'</body>'
'<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/<app>/<theme>.css"></body>
sub_filter_once on;
```

had to change to
```
    proxy_set_header Accept-Encoding "";
    sub_filter
    '</body>'
    '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/<app>/<theme>.css">
    </body>';
    sub_filter_once on;
```
missing `';` at the end of `</body>`

**Comment by GilbN** [comment]
Ah thanks for letting me know. Feel free to make a PR.
