### ISSUE TITLE
qBittorrent scrollbars not being styled in Firefox

### ISSUE THREAD

**Issue by drphero** [themepark-dev/theme.park#521]
**Describe the bug**
The scrollbars for qBittorrent are not getting styled in Firefox. They work fine in Chrome.

**Theme Install Method**
- Webserver subfilter Config

**Application Info**
- qBittorrent 4.3.9

**To Reproduce**
1. Add custom HTTP headers on the Web UI section
```
content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline' theme-park.dev raw.githubusercontent.com use.fontawesome.com; img-src 'self' theme-park.dev raw.githubusercontent.com data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self'; frame-ancestors 'self'; font-src use.fontawesome.com;
```
2. Add the following to nginx qBittorrent conf
```
proxy_set_header Accept-Encoding "";
sub_filter
'</body>'
'<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/qbittorrent/space-gray.css">
</body>';
sub_filter_once on;
```
3. Restart nginx & refresh qBittorrent

**Expected behavior**
The space-gray theme will be applied to qBittorrent, include scrollbars.

**Screenshots**
![firefox](https://github.com/themepark-dev/theme.park/assets/14174687/61bf1949-de8e-45db-a237-6223954e08af)

**Desktop**
 - OS
     - Client: macOS 14.1
     - Server: Debian GNU/Linux 10
 - Browser: Firefox
 - Version: 119.0

**Additional context**
The space-gray theme scrollbars work fine for Sonarr.
The Stylus method has the same problem.
Removing the headers via nginx instead of adding the custom HTTP headers in the WebUI settings has the same problem.

**Comment by GilbN** [comment]
Not seeing this on v123
![image](https://github.com/themepark-dev/theme.park/assets/24592972/1fbdd8a8-eeb4-4d15-8b91-2c81fc1b7dc2)

Using dockermod.
