### ISSUE TITLE
Theme not fully compatible with VueTorrent rewrite

### ISSUE THREAD

**Issue by rauenzi** [themepark-dev/theme.park#522]
**Describe the bug**
Theming partially broken on VueTorrent 2.x.x+. The recently rewrote the entire application in Vue3 and certain aspects of the theme have broken most notably the toolbar and dropdowns.

**Theme Install Method** (Don't skip)
All methods are affected.

**Application Info** (Don't skip)
- Version: 2.x.x+

**To Reproduce**
1. Update VueTorrent to 2.x.x+ 
2. Theme no longer applies to certain parts of the page

**Expected behavior**
The theme to apply especially to major parts of the page. In the case of the screenshot below, the toolbar should be partially transparent and match the theme colors.

**Screenshots**
![image](https://github.com/themepark-dev/theme.park/assets/6865942/baedbf04-613e-4a10-a2ee-58660c836abe)

**Desktop (If applicable) (please complete the following information):**

**Smartphone (If applicable) (please complete the following information):**

**Additional context**

**Comment by QuickSwitchLK** [comment]
I can also confirm this to true. Just updated docker container and have the same issue.

**Comment by Codelica** [comment]
Less noticeable with the "organizr" theme, but the side menu is definitely out of place color-wise.  Will need a look sometime. 👍

**Comment by syphant** [comment]
Confirming the same with VueTorrent v2.7.0

**Comment by GilbN** [comment]
See if develop is better.

**Comment by GilbN** [comment]
Try now.

**Comment by Codelica** [comment]
Thanks, context menus are fixed.  👍
