### ISSUE TITLE
[Addon request] Sonarr/Radarr Icons for Anime (Similar to 4K icon addons)

### ISSUE THREAD

**Issue by brianbuquoi** [themepark-dev/theme.park#528]
For those of us who run 3+ different Sonarr and Radarr instances, it would be cool to have an addon that differentiates the icon for Anime instances like we have for the 4K instances.

Would be extra cool if the Sonarr one had a text option (like 4K does) as well. :)

**Comment by GilbN** [comment]
@brianbuquoi I just merged a PR from @andreirotariu that adds this. Check out the develop branch.

**Comment by GilbN** [comment]
Merged to master
