### ISSUE TITLE
qBittorrent theme in LSIO container is not working

### ISSUE THREAD

**Issue by draculya666** [themepark-dev/theme.park#531]
**Describe the bug**
Accessing the WebUI I get this message in the browser "Unacceptable file type, only regular file is allowed."

**Theme Install Method** (Don't skip)

Docker Mod:
DOCKER_MODS=ghcr.io/gilbn/theme.park:qbittorrent
TP_THEME=overseerr

| qBittorrent theme.park Mod |
Variables set:
'APP_FILEPATH'=/config/qBittorrent/qBittorrent.conf
'TP_DISABLE_THEME'=
'TP_HOTIO'=
'TP_DOMAIN'=
'TP_COMMUNITY_THEME'=
'TP_SCHEME'=
'TP_THEME'=overseerr

No domain set, defaulting to theme-park.dev
No scheme set, defaulting to https
| Downloading WebUI files from github |
Downloading qBittorrent webui to "/themepark"..please wait

Download finished

Downloading qBittorrent webui icons to "/themepark/xxx"..please wait

Download finished

| Adding the stylesheet to html files |
Stylesheet set to overseerr on /themepark/public/index.html

**Application Info** (Don't skip)
- Version: 4.6.2
- Branch: latest
- Container: qBittorrent

(N) 2024-01-14T14:59:12 - Using custom WebUI. Location: "/themepark".
(W) 2024-01-14T14:59:12 - Couldn't load WebUI translation for selected locale (C).
(N) 2024-01-14T14:59:12 - WebUI: Now listening on IP: *, port: 8080
(N) 2024-01-14T14:59:28 - WebAPI login success. IP: ::ffff:172.17.0.1
(N) 2024-01-14T15:00:05 - WebAPI login success. IP: ::ffff:172.17.0.1
(N) 2024-01-14T15:00:08 - WebAPI login success. IP: ::ffff:172.17.0.1
(N) 2024-01-14T15:00:17 - WebAPI login success. IP: ::ffff:172.17.0.1
(W) 2024-01-14T15:01:46 - UPnP/NAT-PMP port mapping failed. Message: "could not map port using UPnP[172.17.0.9]: no router found"
(W) 2024-01-14T15:01:46 - UPnP/NAT-PMP port mapping failed. Message: "could not map port using UPnP[172.17.0.9]: no router found"
(W) 2024-01-14T15:01:46 - UPnP/NAT-PMP port mapping failed. Message: "could not map port using UPnP[172.17.0.9]: no router found"

**To Reproduce**
run the container

**Expected behavior**
getting the login screen of the WebUI

Had to edit qBittorrent.conf to change the variable "WebUI\AlternativeUIEnabled= " from true to false to regain access.

Already submitted to the LSIO github for qbittorrent who directed me report it here.
Inside the container there's no "/themepark" folder.
Worked perfectly until today when the container was updated.

**Comment by Thoroughmas** [comment]
I believe I'm having exactly the same issue (so confirming it's not just you).

**Comment by PJGitHub9** [comment]
wow ok yeah seems like im getting the same issue... today i get the error "Unacceptable file type, only regular file is allowed."

**Comment by PJGitHub9** [comment]
@draculya666 @Tinqerer 

change the docker_mods to this `DOCKER_MODs = ghcr.io/themepark-dev/theme.park:qbittorrent-develop`

**Comment by draculya666** [comment]
> @draculya666 @Tinqerer
> 
> change the docker_mods to this `DOCKER_MODs = ghcr.io/themepark-dev/theme.park:qbittorrent-develop`

Thx :)
It fixed the issue :)
