### ISSUE TITLE
Radarr/Sonarr doesn't load before manual page refresh

### ISSUE THREAD

**Issue by 63OR63** [themepark-dev/theme.park#533]
**Describe the bug**
Opening Radarr/Sonarr with theme.park installed causes the page not to load until manual page refresh (empty page with just a background from installed theme opens for the first time). This happens several times a day, presumably after the cache gets expired/cleared. 

**Theme Install Method**
Docker mod for Linuxserver's image of Radarr/Sonarr

**Application Info (Radarr):**
- Radarr version: 5.2.6.8376
- Environment variables:
    - DOCKER_MODS: ghcr.io/gilbn/theme.park:radarr
    - TP_THEME: space-gray

**Application Info (Sonarr):**
- Sonarr version: 4.0.0.748
- Environment variables:
    - DOCKER_MODS: ghcr.io/gilbn/theme.park:sonarr
    - TP_THEME: space-gray

**To Reproduce**
1) Open Radarr / Sonarr page in incognito window / after clearing cache / some time after previous visit, doesn't matter if using local IP or web address behind a reverse proxy
2) Cry

**Expected behavior**
The page loads correctly.

**Browser Log (before manual page refresh):**
```
react-dom.production.min.js:296 Uncaught (in promise) Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at t.render (react-dom.production.min.js:296:48)
    at g7 (bootstrap.tsx:13:3)
    at index.ts:19:7
```

**Container Log (Sonarr):**
```
[mod-init] Running Docker Modification Logic
[mod-init] Adding gilbn/theme.park:sonarr to container
[mod-init] gilbn/theme.park:sonarr at sha256:352edf32821b08b70ff8ad05ba9d3599b5035147f5997a2d446948f13236842a has been previously applied skipping
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Sonarr: https://sonarr.tv/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

---------------------------
|  Sonarr theme.park Mod  |
---------------------------
Variables set:
'TP_DOMAIN'=
'TP_COMMUNITY_THEME'=
'TP_SCHEME'=
'TP_ADDON'=
'TP_THEME'=space-gray

No domain set, defaulting to theme-park.dev
No scheme set, defaulting to https
[custom-init] No custom files found, skipping...
[Info] Bootstrap: Starting Sonarr - /app/sonarr/bin/Sonarr - Version 4.0.0.748 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] MigrationController: *** Migrating data source=/config/sonarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 *** 
[Debug] MigrationController: Took: 00:00:01.5077935 
[Debug] Microsoft.Extensions.Hosting.Internal.Host: Hosting starting 
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 *** 
[Info] Microsoft.Hosting.Lifetime: Now listening on: http://[::]:8989 
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down. 
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production 
[Info] Microsoft.Hosting.Lifetime: Content root path: /app/sonarr/bin 
[ls.io-init] done.
```

**Host:**
 - OS: Unraid Version: 6.12.6

**Client:**
 - OS: Windows 11 Version 22H2 (OS Build 22621.3007)
 - Browser: Chrome Version 120.0.6099.217 (Official Build) (64-bit), Vivaldi 6.5.3206.53 (Stable channel) (64-bit) 

**Additional info**
- Removing theme.park docker mod gets rid of the error.
- Changing Radarr / Sonarr to the latest dev version doesn't help.
- I started getting this error after upgrading from a year old version of Radarr/Sonarr (sorry, don't know the exact version numbers).

**Comment by GilbN** [comment]
@63OR63 Swtich to `ghcr.io/themepark-dev/theme.park`
