### ISSUE TITLE
SWAG docker mod SVN download errors

### ISSUE THREAD

**Issue by Gex2501** [themepark-dev/theme.park#540]
**Describe the bug**
Files are not being downloaded into the /config/www/themepark folder

**Theme Install Method** (Don't skip)
- SWAG Docker Mod

**Application Info** (Don't skip)
- lscr.io/linuxserver/swag
- Logs
[swag.log](https://github.com/themepark-dev/theme.park/files/14228885/swag.log)

**To Reproduce**
- Add the variable DOCKER_MODS=ghcr.io/themepark-dev/theme.park:swag to your SWAG container.

**Expected behavior**
- CSS files to be downloaded

**Comment by solidslush** [comment]
../branches/${TP_BRANCH}/..  vs ../tree/${TP_BRANCH}/..  ?

**Comment by GilbN** [comment]
Try the develop mod `ghcr.io/themepark-dev/theme.park:swag-develop`

**Comment by solidslush** [comment]
Seems to work for me.

**Comment by GilbN** [comment]
Fix on master
