### ISSUE TITLE
Space Gray --modal-bg-color ends up transparent for Unraid

### ISSUE THREAD

**Issue by javalsu** [themepark-dev/theme.park#548]
Several themes (space-gray is what I tested) results in the modal background to appear as transparent.

**Theme Install Method** (Don't skip)
Installed by referencing the theme url in the theme engine setting of unraid.

**Application Info** (Don't skip)
Unraid
- 6.12.8

**To Reproduce**
(follow the exact steps on the theme engine site)
Install the [Theme Engine](https://forums.unraid.net/topic/87126-plugin-theme-engine-a-webgui-styler/) plugin from the CA appstore and open it.
Set Base Theme to black
Enable Advanced View
Set Enable Theme Engine: to No
Scroll down and set Enable custom styling (below): to Yes
Add the HTML below in the Custom styling (advanced): textarea. Remember to change <THEME> to the theme you want in lowercase.
Go to Settings -> Display Settings and set Header custom text color: to FFF and Header custom background color: to 000

</style>
<link type="text/css" rel="Stylesheet" href="https://theme-park.dev/css/base/unraid/space-gray.css" />

**Expected behavior**
Modal background color should be a gradient

**Screenshots**
![Screenshot 2024-03-09 225320](https://github.com/themepark-dev/theme.park/assets/8809991/7c0cc7d2-a47a-44b4-85ec-56eed5888f30)

**Desktop (If applicable) (please complete the following information):**
 - Windows 11
 - Edge
 - 122.0.2365.80

**Comment by GilbN** [comment]
Try development
