### ISSUE TITLE
[mod-init] (ERROR) gilbn/theme.park:XXX digest could not be fetched from XXX

### ISSUE THREAD

**Issue by tordenflesk** [themepark-dev/theme.park#553]
[mod-init] (ERROR) gilbn/theme.park:radarr digest could not be fetched from ghcr.io
[mod-init] (ERROR) gilbn/theme.park:sonarr digest could not be fetched from registry-1.docker.io

**Comment by GilbN** [comment]
Use ghcr.io/themepark-dev/theme.park
