### ISSUE TITLE
New Major Versions of Sonarr, Radarr, Lidarr, & Prowlarr Causing Theme Issues

### ISSUE THREAD

**Issue by 1ColdAssHonkey** [themepark-dev/theme.park#554]
In the past couple of days, there have been major upgrades in the delvelopment channels for Sonarr, Radarr, Lidarr and Prowlarr.
Since then the themes for each have not been working. It appears that the devs changed some things on the back-end that effect Theme.Parks custom theming.

It is pretty much the same issue as [#499](https://github.com/themepark-dev/theme.park/issues/499), when the .arrs had their last major version upgrade. 

### Theme Install Method (Don't skip)
   theme.park-init] Variables set:
   PUID=99
   PGID=100
   TZ=America/Los_Angeles
   TP_DOMAIN=TP_DOMAIN=10.10.20.49\/themepark
   TP_URLBASE=

###     If using docker mods share your COMPLETE container logs..

    [theme.park-init] Copying nginx files
    [custom-init] No custom files found, skipping...
    [theme.park-init] Copying theme files
    [theme.park-init] Copying mods
    [theme.park-init] Running themes.py and creating CSS files
    [theme.park-init] done.
    [ls.io-init] done.

###     Stylus Config

   None

### Application Info (Don't skip)

   Sonarr:   4.0.3.1486 (Development)
   Radarr:   5.4.6.8723 (Development)
   Lidarr:   2.3.0.4143 (Development)
   Prowlarr: 1.16.1.4420 (Development)
   Theme.Park: 1.16.1

### To Reproduce

   Load Web Browser
   Go to local hosted version of Sonarr, Radarr Lidarr, or Prowlarr.

   I left out the screen shots as each theme referenced above does not currently work at all.

**Comment by 1ColdAssHonkey** [comment]
Found the underlying issue.

Since I have been a long time user, the DOCKER_MODS variable was still pointing to the ghcr.io/gilbn/theme.park, instead of the updated one: ghcr.io/themepark-dev/theme.park.

The unusual thing was that only Sonarr, Radarr, Lidarr, and Prowlarr were not able to pull their themes down from the locally hosted Theme.Park. I have about ten other containers that were still working on the old location.

Went ahead and updated all to avoid any future issues.

Thank you for getting back to me and for taking the time to make such cool mods!

**Comment by GilbN** [comment]
Yeah, I made the old outdated mods private last week, so that's why it didn't work.
