### ISSUE TITLE
Deluge not dark

### ISSUE THREAD

**Issue by KillahB33** [themepark-dev/theme.park#561]
**Describe the bug**

**Theme Install Method** (Don't skip)
  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 51413:51413
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - DELUGE_LOGLEVEL=error #optional
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:deluge
      - TP_THEME=dark
    volumes:
      - /opt/config/deluge:/config
      - /opt/downloads:/downloads
    restart: unless-stopped

Above this is it trying to chown all my stuff, it's on unraid so permissions aren't 1000:1000
**** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****
**** The app may not work properly and we will not provide support for it. ****
[custom-init] No custom files found, skipping...
Connection to 127.0.0.1 58846 port [tcp/*] succeeded!
Connection to 127.0.0.1 8112 port [tcp/*] succeeded!
[ls.io-init] done.

**Application Info** (Don't skip)
Latest

**To Reproduce**
Load it up, tried a restart still default theme

**Expected behavior**
Dark theme

**Desktop (If applicable) (please complete the following information):**
Windows, I tried both brave and chrome and incognito.

**Comment by GilbN** [comment]
try the correct docker mod. that one is old.

**Comment by KillahB33** [comment]
That did it!! Apologies I reviewed the docs and some how missed that.

**Comment by KillahB33** [comment]
That did it!! Apologies I reviewed the docs and some how missed that.
