### ISSUE TITLE
Nginx-Proxy-Manager

### ISSUE THREAD

**Issue by CrazyWolf13** [themepark-dev/theme.park#562]
**Describe the bug**
Hi, how do I apply this when not using docker to deploy, instead using bare metal installation of nginxproxymanager.

**Theme Install Method** (Don't skip)
I tried installing with the docker script, but that did not apply anything.

**Application Info** (Don't skip)
- v2.11.2
- default
- bare metal installation

**To Reproduce**
1. Try to install the script provided for docker
2. see that there changed nothing on the UI.

**Expected behavior**
There should be instructions on how to apply when not using docker.

**Comment by GilbN** [comment]
Just take a look in the script and do the same 
https://github.com/themepark-dev/theme.park/blob/master/docker-mods/nginx-proxy-manager/root/etc/cont-init.d/98-themepark

**Comment by CrazyWolf13** [comment]
Thanks,
Yeah I've just manually copy pasted all the css code in the main.css file located in /app/fronted/css

Here the code, if anyone else needs it (Could potentionally also be added, as it's really really simple):
```
cp /app/frontend/css/main.css /app/frontend/css/main.css.backup
cd /app/frontend/css
> main.css
curl https://raw.githubusercontent.com/themepark-dev/theme.park/develop/css/defaults/transparent.css >> main.css
curl https://raw.githubusercontent.com/themepark-dev/theme.park/develop/css/defaults/placeholders.css >> main.css
curl https://raw.githubusercontent.com/themepark-dev/theme.park/develop/css/theme-options/nord.css >> main.css
curl https://raw.githubusercontent.com/themepark-dev/theme.park/develop/css/base/nginx-proxy-manager/nginx-proxy-manager-base.css >> main.css
```

Where the third entry is the theme of choice.
