### ISSUE TITLE
Detected a little typo

### ISSUE THREAD

**Issue by elchanly** [themepark-dev/theme.park#564]
Trying to setup traefik:
https://docs.theme-park.dev/setup/#traefikyml says to type these in traefik static conf:
experimental:
  plugins:
    theme-park:
_but_ (and thats what made me pull my hair out a little...)  in https://docs.theme-park.dev/setup/#dynamicmiddlewareyml says:
  middlewares:
    sonarr-dark:
      plugin:
        themepark: <<<<<<<<< not theme-park
it's a liiiiiiiiitle typo but for newbies like me can lead  to a few minutes headache....
Thanks!!

**Comment by GilbN** [comment]
Thanks. Fixed.
