### ISSUE TITLE
Text logo addon incorrect image sizing

### ISSUE THREAD

**Issue by h3llrais3r** [themepark-dev/theme.park#648]
**Describe the bug**
Text logo (prowlarr, sonarr) sizes are incorrect

**Theme Install Method** (Don't skip)
- Apache

**Application Info** (Don't skip)
- Prowlarr, Sonarr -> latest versions

**To Reproduce**
Install text-logo addon via apache.
Example for prowlarr:
```
# Create theme_park_name variable
Define theme_park_name nord

<Location "/prowlarr">
	# Proxy http
	ProxyPass "http://localhost:8001/prowlarr"
	ProxyPassReverse "http://localhost:8001/prowlarr"
	
	# Custom stylesheet from theme-park (see https://docs.theme-park.dev/themes/prowlarr/#setup)
	RequestHeader unset Accept-Encoding
	AddOutputFilterByType SUBSTITUTE text/html
	Substitute 's|</head>|<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/prowlarr/${theme_park_name}.css"><link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/addons/prowlarr/prowlarr-text-logo/prowlarr-text-logo.css"></head>|ni'
</Location>
```

**Expected behavior**
Proper logo size, but logo width is not adapted by custom css, because the original `PageHeader.css` seems to have higher priority.

**Screenshots**
![image](https://github.com/user-attachments/assets/9be786c7-9b0b-4360-bdbd-81736b9049d0)

![image](https://github.com/user-attachments/assets/f56b031f-0861-418e-9c4b-9719fd8a324f)

**Desktop (If applicable) (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
When using `!important` for the logo height/width in the addon css, logos are properly sized.

![image](https://github.com/user-attachments/assets/5e279f14-05da-4992-8c2c-27c682f1bc94)

![image](https://github.com/user-attachments/assets/cba5cf02-670a-40e1-92e3-516bd868a6df)

**Comment by h3llrais3r** [comment]
Similar css priority issues with css of header and sidebar, causing the theme colors not applying.

Example: overseerr style
![image](https://github.com/user-attachments/assets/62c837e3-3975-425c-ab67-53a1b2440262)

**Comment by GilbN** [comment]
What app versions are you using?

**Comment by GilbN** [comment]
Also you need to substitute the body, not the head. https://docs.theme-park.dev/themes/sonarr/#installation

**Comment by h3llrais3r** [comment]
> Also you need to substitute the body, not the head. https://docs.theme-park.dev/themes/sonarr/#installation

Thanks for pointing it out... I based myself on the general setup for Apache, which is telling me to substitute the head.
Let me try it out with the body instead. I'll keep you posted.

**Comment by GilbN** [comment]
Great!  Yeah the body substitution is a relatively new thing for the arr apps.
